
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 27 23:22:16 CEST 2018
//----------------------------------------------------

package parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACK = 14;
  public static final int LT = 23;
  public static final int NE = 21;
  public static final int IDENT = 32;
  public static final int ASGN = 19;
  public static final int ELSE = 3;
  public static final int PLUS = 27;
  public static final int RPAREN = 12;
  public static final int LCURL = 16;
  public static final int WHILE = 10;
  public static final int SLASH = 29;
  public static final int STAR = 28;
  public static final int LBRACK = 13;
  public static final int REF = 7;
  public static final int IF = 4;
  public static final int COLON = 20;
  public static final int GT = 17;
  public static final int LPAREN = 11;
  public static final int LE = 24;
  public static final int OF = 5;
  public static final int INTLIT = 31;
  public static final int SEMIC = 30;
  public static final int TYPE = 8;
  public static final int COMMA = 25;
  public static final int EOF = 0;
  public static final int MINUS = 26;
  public static final int GE = 18;
  public static final int error = 1;
  public static final int PROC = 6;
  public static final int EQ = 22;
  public static final int RCURL = 15;
  public static final int ARRAY = 2;
  public static final int VAR = 9;
}

