#!/bin/bash


//make dist-clean
//make

echo ""
echo "================================================================"
echo ""

echo "list program: $1 "
echo "================================================================"
echo ""
cat $1

echo ""
echo "================================================================"
echo ""
echo "executing file: $1"
./spl --tables --vars $1 out.txt
 
